_target_: lightning.pytorch.trainer.Trainer

default_root_dir: ${paths.output_dir}

min_epochs: 1 # prevents early stopping
max_epochs: 280

accelerator: gpu
devices: 1

num_sanity_val_steps: 0

# mixed precision for extra speed-up
# precision: 16

# perform a validation loop every N training epochs
check_val_every_n_epoch: 1

# set True to ensure deterministic results
# makes training slower but gives more reproducibility than just setting seeds
deterministic: False
